name: "Pre-RFC Discussion"
description: "Discuss a problem or idea before writing an RFC."
labels: ["pre-rfc"]
assignees: [bwnodak]
body:
  - type: markdown
    attributes:
      value: "## Pre-RFC Discussion"
      
  - type: textarea
    attributes:
      label: "Summary"
      description: "What is the core problem or idea that you're proposing to solve or implement? Provide a brief description."
      placeholder: "Briefly describe the core problem or idea."

  - type: textarea
    attributes:
      label: "Why is it important?"
      description: "Explain why this problem is worth addressing. What value does it bring to the team/project?"
      placeholder: "Explain the importance of addressing this problem or idea."

  - type: textarea
    attributes:
      label: "Initial Thoughts or Proposed Solutions"
      description: "Do you have any ideas on how to solve it? If not, use this section to gather initial feedback and brainstorm."
      placeholder: "Provide any initial thoughts or proposed solutions, or leave this for brainstorming."

  - type: textarea
    attributes:
      label: "Risks and Concerns"
      description: "What are the risks, challenges, or possible blockers?"
      placeholder: "List any risks or concerns."

  - type: checkboxes
    attributes:
      label: "Shepherding"
      description: "Please check the relevant option."
      options:
        - label: "I am willing to shepherd this issue into an RFC if it gains traction."
          required: false
        - label: "I am looking for a shepherd or co-shepherd for this effort."
          required: false
